### ISSUE TITLE
java.lang.NullPointerException at org.reflections.vfs.Vfs

### ISSUE THREAD

**Issue by cforce** [ronmamo/reflections#111]
[WARNING] could not create Dir using directory from url file:/C:/Users/ddsdds/git/core-library-starter-cloud/target/classes. skipping.
java.lang.NullPointerException
    at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
    at org.reflections.Reflections.scan(Reflections.java:236)
    at org.reflections.Reflections.scan(Reflections.java:203)
    at org.reflections.Reflections.<init>(Reflections.java:128)
    at org.reflections.Reflections.<init>(Reflections.java:169)
    at org.reflections.Reflections.<init>(Reflections.java:142)

**Comment by wwadge** [comment]
Just hit this same bug; in this method: 
```
   public boolean matches(URL url) {
                return url.getProtocol().equals("file") && !url.toExternalForm().contains(".jar") &&
                        getFile(url).isDirectory();
            }
```
getFile(url) can return null if it doesn't find the file/directory.
