### ISSUE TITLE
Filters seem to not do anything?

### ISSUE THREAD

**Issue by dotSp0T** [ronmamo/reflections#168]
When I run the following snippet...
```
REFLECTIONS = new Reflections(
	            new ConfigurationBuilder()
	            .setUrls(ClasspathHelper.forJavaClassPath())
	            .setScanners(new SubTypesScanner(true))
	            .filterInputsBy(
	                    new FilterBuilder()
	                    .excludePackage("java.")
	                    .excludePackage("javax.")
	                    .add((s) -> {return s.contains(".class");}))
	            );
```
..I get inter alia the following errors from reflections...
```
org.reflections.ReflectionsException: could not create class object from file ch/qos/logback/classic/gaffer/ConfigurationDelegate.groovy
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)

...

08:12:57.154 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.OutputStream -> java.io.ByteArrayOutputStream

...

08:12:57.167 [main] WARN  org.reflections.Reflections - could not get type for name javax.servlet.ServletContextListener from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.ServletContextListener
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
```
...even though I've added filters & predicates to remove files that aren't classe, as well as the java and javax packages!

Is it me misunderstanding/doing something wrong, or is this an actual bug?

**Comment by digulla** [comment]
I have a similar problem where Reflections suddenly starts to complain about MANIFEST.MF:

```
DEBUG  [2017-11-10 15:35:25,123] 15355  [Thread-9] org.reflections.Reflections          - Alarm: Exception occurred could not scan file META-INF/MANIFEST.MF in url jar:file:/opt/impaqt-swisscom/lib/e
org.reflections.ReflectionsException: could not create class object from file META-INF/MANIFEST.MF
        at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
        at org.reflections.Reflections.scan(Reflections.java:253)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
```

I'm specifying packages in the configuration plus when I write a unit test, then I **don't** get this output! Currently, I'm stumped what the problem could be.

**Comment by ts14ic** [comment]
The behavior in OP is likely caused by `configurationBuilder.setExpandSuperTypes(true)` set by default. The stacktraces contain `expandSuperTypes`.  
Explicitly calling `setExpandSuperTypes(false)` will help, although I'm not exactly sure what it does.  

Also, it seems that `expandSuperTypes` is applied AFTER filters.

**Comment by ts14ic** [comment]
p.s. Initially I thought the problem was caused, because the `FilterBuilder` uses a somewhat inconsistent combination of `OR` and `AND` semantics, and though that it was the problem.  

A combination of `include + exclude` includes all classes allowed by first predicate and then excludes the remaining ones using the second predicated. An `AND` semantic is implied (the filter is incremental). Looks ok.

A combination of `exclude + exclude` uses the `AND` semantic as well (the filter is incremental).

But a combination of `include + include` is using the `OR` semantic of - a class is allowed if any of the predicates pass. The filter is not incremental here.

Say, I'm using `includePackage("foo")` and `include(".*BarClass")`.  
I'd expect only `foo....BarClass` to be included, but it actually includes anything that has the package `foo` OR has the `BarClass` ending.  

I suppose the problem lies here:  
```java
public boolean apply(String regex) {
    boolean accept = chain == null || chain.isEmpty() || chain.get(0) instanceof Exclude;

    if (chain != null) {
        for (Predicate<String> filter : chain) {
            if (accept && filter instanceof Include) {continue;} //skip if this filter won't change
            if (!accept && filter instanceof Exclude) {continue;}
            accept = filter.apply(regex);
            if (!accept && filter instanceof Exclude) {break;} //break on first exclusion
        }
    }
    return accept;
}
```

I can create a separate issue :).

**Comment by MatthewRyanRead** [comment]
Separate includes _must_ be `OR`'d, otherwise you could never include two thing with nothing in common.  If you wanted only `foo....BarClass`, you would specify that directly with `include("foo.*.BarClass")` (and `include("foo.BarClass")` if needed).

**Comment by ts14ic** [comment]
Well, it was long ago, so I don't remember the details.  
I think my intention was to suggest explicit and/or operators, instead of seemingly inconsistent/undcomented OR/AND semantics.
