### ISSUE TITLE
FileNotFoundException for jsf-nls.jar in Websphere 8.5.5.7

### ISSUE THREAD

**Issue by djechelon** [ronmamo/reflections#216]
Hello,

we are having an issue scanning our classpath for classes extending Spring's base `ApplicationEvent`. Our code works on any server except Websphere 8.5.5.7 which *could* show a boot classpath misconfiguration.

```
java.util.concurrent.ExecutionException: org.reflections.ReflectionsException: Could not open url connection
	at java.util.concurrent.FutureTask.report(FutureTask.java:134) ~[?:1.7.0]
	at java.util.concurrent.FutureTask.get(FutureTask.java:200) ~[?:1.7.0]
	at org.reflections.Reflections.scan(Reflections.java:213) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:123) ~[reflections-0.9.11.jar:?]
	at org.zighinetto.djechelon.NotificationManagerImpl.afterPropertiesSet(NotificationManagerImpl.java:134) ~[acme-web-3.7.0.4.jar:20170922085938]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 40 more
Caused by: org.reflections.ReflectionsException: Could not open url connection
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:37) ~[reflections-0.9.11.jar:?]
	at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:243) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections$1.run(Reflections.java:198) ~[reflections-0.9.11.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:483) ~[?:1.7.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:274) ~[?:1.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157) ~[?:1.7.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627) ~[?:1.7.0]
	at java.lang.Thread.run(Thread.java:809) ~[?:1.7.0]
Caused by: java.io.FileNotFoundException: /var/opt/six/websphere/AppServer/lib/jsf-nls.jar (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[?:1.7.0]
	at java.io.FileInputStream.<init>(FileInputStream.java:158) ~[?:1.7.0]
	at java.io.FileInputStream.<init>(FileInputStream.java:113) ~[?:1.7.0]
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:104) ~[?:1.7.0]
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:202) ~[?:1.7.0]
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:36) ~[reflections-0.9.11.jar:?]
	at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:243) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections$1.run(Reflections.java:198) ~[reflections-0.9.11.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:483) ~[?:1.7.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:274) ~[?:1.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157) ~[?:1.7.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627) ~[?:1.7.0]
	at java.lang.Thread.run(Thread.java:809) ~[?:1.7.0]
```

Following is our code:

```
    private final Set<Class<? extends ApplicationEvent>> allEventClasses = new LinkedHashSet<>();
    private String[] packagesToScan = { "org.zighinetto", "org.zighimania",
            // "org.springframework"
    };

    @Override
    public void afterPropertiesSet() throws Exception
    {
        super.afterPropertiesSet();
        allEventClasses.clear();
        // Scan for modules
        log.info("Scanning packages for events");

        ExecutorService exec = Executors.newFixedThreadPool(4);
        try
        {
            Reflections reflections = new Reflections(ConfigurationBuilder.build((Object[]) packagesToScan).setExecutorService(exec));

            Predicate<Class<?>> classFilter = Predicates.not(new Predicate<Class<?>>()
            {
                @Override
                public boolean apply(Class<?> candidate)
                {
                    return candidate.isMemberClass() || candidate.isLocalClass() || candidate.isAnonymousClass();
                }
            });
            allEventClasses.addAll(Sets.filter(reflections.getSubTypesOf(ApplicationEvent.class), classFilter));
        }
        finally
        {
            exec.shutdown();
        }

        log.info("Complete scan for events. Found {} events", allEventClasses.size());
        for (Class<? extends ApplicationEvent> evtClass : allEventClasses)
            log.debug("Found class {}", evtClass.getCanonicalName());

    }
```

We are using Reflections on a simple thread pool executor to scan for all subclasses of Spring's ApplicationEvent under the assigned packages.
The problem is that in Websphere the boot classpath contains a missing jar `/var/opt/six/websphere/AppServer/lib/jsf-nls.jar` which does not prevent applications from starting/working.

Our application is a web application (WAR archive) and classpaths we are interested in are 99.99999% `WEB-INF/lib/*.jar`.

We also work a lot under Eclipse, so our classpath scanning must be enough smart to pick uncompressed classes when running in Eclipse and jars when running in the application server

## Some reading

 - https://www.ibm.com/developerworks/community/forums/html/topic?id=4f35b3a3-0530-4a6c-9844-227355ce809b

In the above discussion IBM says everything is OK. If someone wants the broken classpath to be amended they have to submit a `Product Modification Request` :cold_sweat: to IBM

- http://www-01.ibm.com/support/docview.wss?uid=swg1PM20405

The above is related to an official patch for WS 7

- https://github.com/elastic/elasticsearch/issues/15052

In the above discussion participants are criticizing that `CheckJarHell` is too strict on missing jar files. One important thing I would like to quote

@tberne --> https://github.com/elastic/elasticsearch/issues/15052#issuecomment-160200426

> BTW, in Java SE Documentation, it is said that "Classpath entries that are neither directories nor archives (.zip or .jar files) nor * are ignored.".

## Our analysis

I found this possibly causing jsf-nls.jar to be added to url scan:

ConfigurationBuilder.java: 117
```
        if (builder.getUrls().isEmpty()) {
            if (classLoaders != null) {
                builder.addUrls(ClasspathHelper.forClassLoader(classLoaders)); //default urls getResources("")
            } else {
                builder.addUrls(ClasspathHelper.forClassLoader()); //default urls getResources("")
            }
        }
```
We are not providing URLs because we will very likely break compatibility with other application servers and IDEs, so the idea of "hey buddy, scan all the classpath and tell us what you found" seems reasonable to us.

Exception is simply caused by JarInputDir.java throwing a ReflectionsException when unable to open jar stream. The exception is propagated and the process is stopped.
```
                    {
                        try { jarInputStream = new JarInputStream(url.openConnection().getInputStream()); }
                        catch (Exception e) { throw new ReflectionsException("Could not open url connection", e); }
                    }
```
## The very problem is

That our customer refuses to make any change to their configuration even if blatantly wrong. Actually they are defending themselves saying that IBM said there is nothing wrong with configuration.

So they demand us to fix the code, but as you can see there is no simple way to amend application code that uses Reflections if not for the explicit URLs. Also, we noted that we can't reproduce the issue locally on our WAS installation which is very slightly different from customer's revision.

And of course accessing customer's systems is impossible for us, not to mention debugging. We also use Reflections in many places in our code.

## Conclusion

I would like to suggest amending Reflections's way of handling missing classpath entries following https://github.com/elastic/elasticsearch/issues/15052#issuecomment-160200426

I would recommend to ignore missing classpath entries, perhaps printing a huge warning.

Do you think it's feasible? I am asking this just because the commenter I mentioned said it's standard Java specifications.

Thank you ronmamo!

**Comment by djechelon** [comment]
May be related: #178 

Since we have specified packages, ClasspathHelper could be still returning URLs for root package including jsf
