### ISSUE TITLE
Excessive WARN log noise in 0.9.11

### ISSUE THREAD

**Issue by jaxley** [ronmamo/reflections#252]
Version 0.9.11 generates a ton of noise in the logs, such as:

```
WARN  [2018-11-07 09:47:39,252] org.reflections.Reflections: could not get type for name org.junit.runners.BlockJUnit4ClassRunner from any class loader
! java.lang.ClassNotFoundException: org.junit.runners.BlockJUnit4ClassRunner
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
```

See also https://groups.google.com/forum/#!topic/dropwizard-user/I0K4e0APudY for another take

Downgrading to 0.9.10 avoids these excessive log messages.  dropwizard-swagger uses this as a transitive dependency.  Here's a workaround for gradle:

```
ext {
        dropwizardVersion = "1.3.7"
        orgReflectionsVersion = "0.9.10"
}
    compile("com.smoketurner:dropwizard-swagger:${dropwizardVersion}-1") {
        // version 0.9.11 generates tons of noise in WARN logs about types it can't find:  https://groups.google.com/forum/#!topic/dropwizard-user/I0K4e0APudY
        exclude(group: "org.reflections")
    }
    compile "org.reflections:reflections:${orgReflectionsVersion}"
```

**Comment by gregflynn** [comment]
Ran into this adding swagger-core to a dropwizard project, downgrading to 0.9.10 worked for me as well.

**Comment by tangdu** [comment]
I also have this problem. Downgrading to 0.9.10 will do.

**Comment by mbaldini** [comment]
Ran into the same issue. The same downgrade to 0.9.10 worked.
Figured I would include a POM sample since a gradle one is listed above

```
<dependency>
    <groupId>com.smoketurner</groupId>
    <artifactId>dropwizard-swagger</artifactId>
    <version>${dropwizard.swagger.version}</version>
    <exclusions>
        <exclusion>
            <!--Exclude 0.9.11  -->
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<!--Include version 0.9.10  -->
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.10</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>annotations</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by darewreck54** [comment]
If I downgrade to 0.9.10, I'll get the following error

```
INFO  [2020-05-02 16:53:18,442] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: swagger-oauth2-connect for path /oauth2-redirect.html/*
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.setExpandSuperTypes(Z)Lorg/reflections/util/ConfigurationBuilder;
        at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:284)
        at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)
        at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
        at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
```

This is with a gradle of

```
    compile("io.dropwizard:dropwizard-core:2.0.6") {
        exclude group: "org.reflections", module: "reflections"
    }
    compile group: 'com.smoketurner', name: 'dropwizard-swagger', version: '2.0.0-1'
    compile group: 'io.swagger.core.v3', name: 'swagger-core', version: '2.1.2'
    compile group: 'ru.vyarus', name: 'dropwizard-guicey', version: '5.0.1'
    compile group: 'com.google.inject', name: 'guice', version: '4.2.3'
    implementation('org.reflections:reflections:0.9.10') {
        force = true
    }
```

If I use either 0.9.11 or 0.9.12, I get the following error:

```
NFO  [2020-05-02 16:27:49,677] org.reflections.Reflections: Reflections took 3310 ms to scan 1 urls, producing 46190 keys and 93336 values 
WARN  [2020-05-02 16:27:49,699] org.reflections.Reflections: could not get type for name org.zeroturnaround.javarebel.ClassEventListener from any class loader
! java.lang.ClassNotFoundException: org.zeroturnaround.javarebel.ClassEventListener
! at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name org.zeroturnaround.javarebel.ClassEventListener
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:288)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at 
WARN  [2020-05-02 16:27:49,702] org.reflections.Reflections: could not get type for name groovy.lang.Closure from any class loader
! java.lang.ClassNotFoundException: groovy.lang.Closure
! at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
```

Any help appreciated
Thanks,
Derek

**Comment by tatianajiselle** [comment]
came to say im getting the same thing. Its something to do with the version of DropWizard (im using 2.0.10) and the version of the Swagger bundle (2.0.0)....

When i drop to  these version i see no errors:
`
 <dropwizard.version>1.3.8</dropwizard.version>
  <dropwizard-swagger.version>1.3.7-1</dropwizard-swagger.version>
`

**Comment by priyadharshini16** [comment]
> If I downgrade to 0.9.10, I'll get the following error
> 
> ```
> INFO  [2020-05-02 16:53:18,442] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: swagger-oauth2-connect for path /oauth2-redirect.html/*
> java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.setExpandSuperTypes(Z)Lorg/reflections/util/ConfigurationBuilder;
>         at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:284)
>         at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)
>         at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
>         at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
>         at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
>         at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
>         at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
>         at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
>         at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
>         at io.dropwizard.cli.Cli.run(Cli.java:78)
> ```
> 
> This is with a gradle of
> 
> ```
>     compile("io.dropwizard:dropwizard-core:2.0.6") {
>         exclude group: "org.reflections", module: "reflections"
>     }
>     compile group: 'com.smoketurner', name: 'dropwizard-swagger', version: '2.0.0-1'
>     compile group: 'io.swagger.core.v3', name: 'swagger-core', version: '2.1.2'
>     compile group: 'ru.vyarus', name: 'dropwizard-guicey', version: '5.0.1'
>     compile group: 'com.google.inject', name: 'guice', version: '4.2.3'
>     implementation('org.reflections:reflections:0.9.10') {
>         force = true
>     }
> ```
> 
> If I use either 0.9.11 or 0.9.12, I get the following error:
> 
> ```
> NFO  [2020-05-02 16:27:49,677] org.reflections.Reflections: Reflections took 3310 ms to scan 1 urls, producing 46190 keys and 93336 values 
> WARN  [2020-05-02 16:27:49,699] org.reflections.Reflections: could not get type for name org.zeroturnaround.javarebel.ClassEventListener from any class loader
> ! java.lang.ClassNotFoundException: org.zeroturnaround.javarebel.ClassEventListener
> ! at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> ! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
> ! ... 14 common frames omitted
> ! Causing: org.reflections.ReflectionsException: could not get type for name org.zeroturnaround.javarebel.ClassEventListener
> ! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
> ! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
> ! at org.reflections.Reflections.<init>(Reflections.java:126)
> ! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:288)
> ! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)
> ! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
> ! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
> ! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
> ! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
> ! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
> ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
> ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
> ! at io.dropwizard.cli.Cli.run(Cli.java:78)
> ! at io.dropwizard.Application.run(Application.java:94)
> ! at 
> WARN  [2020-05-02 16:27:49,702] org.reflections.Reflections: could not get type for name groovy.lang.Closure from any class loader
> ! java.lang.ClassNotFoundException: groovy.lang.Closure
> ! at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> ! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> ! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
> ```
> 
> I also tried excluding guice and findbugs from the reflectionand still the same error:
> 
> ```
>     compile("org.reflections:reflections:0.9.10") {
>         // version 0.9.11 generates tons of noise in WARN logs about types it can't find:  https://groups.google.com/forum/#!topic/dropwizard-user/I0K4e0APudY
>         exclude(group: "com.google.guava")
>         exclude(group: "com.google.code.findbugs")
>     }
> ```
> 
> error;
> 
> ```
> java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.setExpandSuperTypes(Z)Lorg/reflections/util/ConfigurationBuilder;
>         at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:284)
>         at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250)
>         at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
>         at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
>         at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
>         at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
>         at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
>         at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
>         at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
>         at io.dropwizard.cli.Cli.run(Cli.java:78)
>         at io.dropwizard.Application.run(Application.java:94)
> ```
> 
> Any help appreciated
> Thanks,
> Derek

@darewreck54 Were you able to fix this issue?
