### ISSUE TITLE
Exception thrown when running from war package

### ISSUE THREAD

**Issue by a13519** [ronmamo/reflections#321]
It's a simple practice with SpringBoot to find specific annotation type:

`Set<Class<?>> annotatedSocket = new Reflections("net.zousys.package") .getTypesAnnotatedWith(SocketPluggin.class);`

It was running well within the IntelliJ IDE. When I use Gradle to package it as War and run it by 

`java -jar DemoApp.war`

It thrown following exception:
`2021-03-25 15:58:05.285 ERROR - SpringApplication : Application run failed
java.lang.ExceptionInInitializerError
        at net.zousys.trading.context.console.ConsoleConfiguration.postProcessBeanFactory(ConsoleConfiguration.java:34)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:181)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at net.zousys.trading.StrategyApplication.main(StrategyApplication.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:664)
        at java.base/java.util.zip.ZipFile.access$500(ZipFile.java:76)
        at java.base/java.util.zip.ZipFile$ZipEntryIterator.<init>(ZipFile.java:475)
        at java.base/java.util.zip.ZipFile.entries(ZipFile.java:514)
        at java.base/java.util.jar.JarFile.access$001(JarFile.java:131)
        at java.base/java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:504)
        at java.base/java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:501)
        at java.base/java.util.jar.JarFile.stream(JarFile.java:549)
        at org.reflections.vfs.ZipDir.lambda$getFiles$2(ZipDir.java:21)
        at org.reflections.Reflections.scan(Reflections.java:260)
        at org.reflections.Reflections.scan(Reflections.java:216)
        at org.reflections.Reflections.<init>(Reflections.java:137)
        at org.reflections.Reflections.<init>(Reflections.java:182)
        at org.reflections.Reflections.<init>(Reflections.java:155)
        at net.zousys.trading.context.config.Infrastructure.<init>(Infrastructure.java:15)
        at net.zousys.trading.context.config.InfraFacility.<init>(InfraFacility.java:26)
        at net.zousys.trading.context.config.InfraFacility.<clinit>(InfraFacility.java:32)
`
It can run without issue before I adapt the reflections library into the build.gradle:
`implementation 'org.reflections:reflections:0.9.12'`

Any clue to fix it?

Thanks,
Song

**Comment by ambraspace** [comment]
Yes, the same happens when running from JAR file. :(

**Comment by ambraspace** [comment]
I wanted to update to reflections-0.9.12 since reflections-0.9.10 pulls guava-15.0 and this is in collision with guava-29.0 pulled by firebase-admin-7.1.0.
In the end I decided to keep reflections-0.9.10, but I had to add guava-15.0 exclusions to pom.xml file.
So, I will keep it like this until this issue is resolved...
