### ISSUE TITLE
scan bug occur in version 0.9.12 but not in 0.9.11

### ISSUE THREAD

**Issue by hoorf** [ronmamo/reflections#328]
springboot multi module project ,package a fat jar, init scan like this:
```java
public class ReflectionUtils extends org.reflections.ReflectionUtils {

    static Reflections reflections = null;

    static {
        String[] basePackages = SpringContextHolder.getBasePackages();
       // String[] basePackages = new String[]{"org.github.hoorf.account"};
        log.debug("Scan base package {}",basePackages);
        reflections = new Reflections(basePackages);
    }


    public static <T> Set<Class<? extends T>> getSubTypesOf(Class<T> type) {
        return reflections.getSubTypesOf(type);
    }

}
```

in version 0.9.12 package to jar run ,occur exception :
```java
Caused by: java.lang.IllegalStateException: zip file closed
account    |    at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669) ~[na:1.8.0_111]
account    |    at java.util.zip.ZipFile.access$200(ZipFile.java:60) ~[na:1.8.0_111]
account    |    at java.util.zip.ZipFile$ZipEntryIterator.<init>(ZipFile.java:484) ~[na:1.8.0_111]
account    |    at java.util.zip.ZipFile.entries(ZipFile.java:537) ~[na:1.8.0_111]
account    |    at java.util.jar.JarFile.access$001(JarFile.java:71) ~[na:1.8.0_111]
account    |    at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:250) ~[na:1.8.0_111]
account    |    at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:247) ~[na:1.8.0_111]
account    |    at java.util.jar.JarFile.stream(JarFile.java:279) ~[na:1.8.0_111]
account    |    at org.reflections.vfs.ZipDir.lambda$getFiles$2(ZipDir.java:21) ~[reflections-0.9.12.jar!/:na]
account    |    at org.reflections.Reflections.scan(Reflections.java:260) ~[reflections-0.9.12.jar!/:na]
account    |    at org.reflections.Reflections.scan(Reflections.java:216) ~[reflections-0.9.12.jar!/:na]
account    |    at org.reflections.Reflections.<init>(Reflections.java:137) ~[reflections-0.9.12.jar!/:na]
account    |    at org.reflections.Reflections.<init>(Reflections.java:182) ~[reflections-0.9.12.jar!/:na]
```

but without packaging to jar,run in IDEA by Main class, it run normal

when switch to version 0.9.11 ,it both run normal (jar & normal main Class run )

**Comment by hoorf** [comment]
just spring version bug
