### ISSUE TITLE
`reflections.getTypesAnnotatedWith` crashes for annotated module-info.java classes

### ISSUE THREAD

**Issue by soc** [ronmamo/reflections#329]
```
reflections.getTypesAnnotatedWith(Deprecated.class, true)
```

... with this `module-info.java` ...

```
@Deprecated
module foo.bar { ... }
```
... crashes with:

```
could not get type for name module-info from any class loader
org.reflections.ReflectionsException: could not get type for name module-info
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312) ~[reflections-0.9.12.jar:?]
	at org.reflections.ReflectionUtils.lambda$forNames$22(ReflectionUtils.java:330) ~[reflections-0.9.12.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) [?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:332) [reflections-0.9.12.jar:?]
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:431) [reflections-0.9.12.jar:?]
	at ...
Caused by: java.lang.NoClassDefFoundError: module-info is not a class because access_flag ACC_MODULE is set
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:310) ~[reflections-0.9.12.jar:?]
	... 14 more
```

**Comment by JJBRT** [comment]
Have you tried with [this](https://github.com/burningwave/core/wiki/Finding-all-classes-for-module-name-(Java-9-and-later))?

**Comment by soc** [comment]
That's a completely different piece of software doing something completely different.

**Comment by JJBRT** [comment]
> That's a completely different piece of software doing something completely different.

The example I posted searches for all classes by module name in the classpath so you can replace the ClassCriteria with
`ClassCriteria.create().allThoseThatMatch((currentScannedClass) ->
                        currentScannedClass.getModule().getAnnotation(Deprecated.class) != null
                    )`

**Comment by ronmamo** [comment]
hey @JJBRT , fuck off!
