### ISSUE TITLE
Different Behaviour with Java 17.0.3-17.34.19 

### ISSUE THREAD

**Issue by kesslerd** [ronmamo/reflections#395]
We wanted to upgrade our Project to Java Zulu 17.0.3-17.34.19 and run into the issue that org.reflections does not find the same classes anymore. The below issue happens with 0.9.11 and 0.10.2. I did not test other versions.

With the newer Java_Version we noticed a different behaviour in `org.reflections.vfs.JbossDir#createDir` for vfs-jar urls.

The call ` VirtualFile virtualFile = (VirtualFile) url.openConnection().getContent();` does not return an Object of type `org.jboss.vfs.VirtualFile` which leads to a ClassCastExcpetion

Investigating further we noticed that `org.jboss.vfs.protocol.AbstractURLConnection#getContentType` now returns a value of `"application/java-archive"` instead of `null`. 
Therefore, an object of the type `org.jboss.vfs.VirtualJarFileInputStream` is returned by the `url.openConnection().getContent()` call.

`sun.net.www.MimeTable.loadTable();` does not return the same values anymore and org.reflections runs into issues.

```
13:25:31,826 WARN  [org.reflections.Reflections] (ServerService Thread Pool -- 84) could not create Dir using jboss_vfs from url vfs:/Users/user/Documents/demo/rest/build/libs/exploded/rest.war/WEB-INF/lib/idlib.jar/. skipping.: java.lang.ClassCastException: class org.jboss.vfs.VirtualJarInputStream cannot be cast to class org.jboss.vfs.VirtualFile (org.jboss.vfs.VirtualJarInputStream and org.jboss.vfs.VirtualFile are in unnamed module of loader 'org.jboss.vfs@3.2.16.Final' @3ab39c39)
	at deployment.rest.war//org.reflections.vfs.JbossDir.createDir(JbossDir.java:19)
	at deployment.rest.war//org.reflections.vfs.Vfs$DefaultUrlTypes$4.createDir(Vfs.java:259)
	at deployment.rest.war//org.reflections.vfs.Vfs.fromURL(Vfs.java:103)
	at deployment.rest.war//org.reflections.vfs.Vfs.fromURL(Vfs.java:95)
	at deployment.rest.war//org.reflections.Reflections.lambda$scan$2(Reflections.java:176)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at deployment.rest.war//org.reflections.Reflections.scan(Reflections.java:173)
	at deployment.rest.war//org.reflections.Reflections.<init>(Reflections.java:126)
	at deployment.rest.war//com.example.demo.HelloApplication.getClasses(HelloApplication.java:18)
```

Small demo project
[demo.zip](https://github.com/ronmamo/reflections/files/8562783/demo.zip)

**Comment by kesslerd** [comment]
I could also reproduce this behaviour with the OpenJDK.

**Comment by jcputney** [comment]
We're running into this issue as well when trying to upgrade to Azul Zulu 17.0.3

Anyway we can get a patch release out for this PR?

**Comment by Philipp-Borchert-ISH** [comment]
btw. it seems that this is also tracked on the "other" side in redhat Jira for jboss-vfs: https://issues.redhat.com/browse/WFLY-16322
