### ISSUE TITLE
ClassCastException when running on Wildfly and Java 17

### ISSUE THREAD

**Issue by dbaldes** [ronmamo/reflections#429]
I get the following exception when running org.reflections 0.10.2 on Widlfly 26.1.1 and Java 17:

``` 
WARN  [org.reflections.Reflections] could not create Dir using jboss_vfs from url vfs:/xxxxx.jar/. skipping.: java.lang.ClassCastException: class org.jboss.vfs.VirtualJarInputStream cannot be cast to class org.jboss.vfs.VirtualFile (org.jboss.vfs.VirtualJarInputStream and org.jboss.vfs.VirtualFile are in unnamed module of loader 'org.jboss.vfs@3.2.16.Final' @3f3afe78)
	at xxxx.war//org.reflections.vfs.JbossDir.createDir(JbossDir.java:19)
	at xxxx.war//org.reflections.vfs.Vfs$DefaultUrlTypes$4.createDir(Vfs.java:259)
```

Apparently, url.openConnection().getContent() returns a VirtualJarInputStream on Java 17 instead of the expected VirtualFile.

**Comment by dbaldes** [comment]
This seems to be a duplicate of https://github.com/ronmamo/reflections/issues/427

**Comment by dbaldes** [comment]
This seems to be caused by: https://issues.redhat.com/browse/WFLY-16322
And is fixed in jboss-vfs v.3,2,17.Final
