### ISSUE TITLE
Exception in Reflection helpers

### ISSUE THREAD

**Issue by TheEricWilson** [ronmamo/reflections#48]
Exception in thread "main" org.reflections.ReflectionsException: could not get type for name org.reflections.serializers.JsonSerializer$1
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:389)
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:398)
	at org.reflections.Reflections.getSubTypesOf(Reflections.java:357)
	at com.costco.rnd.Bulkthing.doWork(Bulkthing.java:31)
	at com.costco.rnd.Bulkthing.main(Bulkthing.java:19)

Using the following dependencies
```  
<dependencies>
       <dependency>
         <groupId>org.reflections</groupId>
         <artifactId>reflections</artifactId>
         <version>0.9.9</version>
     </dependency>
     <dependency>
     	<groupId>org.neo4j</groupId>
    	<artifactId>neo4j-rest-graphdb</artifactId>
    	<version>1.9.3-SNAPSHOT</version>
     </dependency>
  </dependencies>
```

In this basic class

```java
package com.costco.rnd;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import org.reflections.Reflections;
import org.reflections.scanners.ResourcesScanner;
import org.reflections.scanners.SubTypesScanner;
import org.reflections.util.ClasspathHelper;
import org.reflections.util.ConfigurationBuilder;
import org.reflections.util.FilterBuilder;

public class Bulkthing {
	 Reflections reflections;
	 public static void main(String[] args){
		 Bulkthing myThing = new Bulkthing();
		 myThing.doWork();
	 }
	 
	 public void doWork(){
		 List<ClassLoader> classLoadersList = new LinkedList<ClassLoader>();
		 classLoadersList.add(ClasspathHelper.contextClassLoader());
		 classLoadersList.add(ClasspathHelper.staticClassLoader());

		  reflections = new Reflections(new ConfigurationBuilder()
		     .setScanners(new SubTypesScanner(false /* don't exclude Object.class */), new ResourcesScanner())
		     .setUrls(ClasspathHelper.forClassLoader(classLoadersList.toArray(new ClassLoader[0])))
		     .filterInputsBy(new FilterBuilder().include(FilterBuilder.prefix("org"))));
		  Set<Class<?>> classes = reflections.getSubTypesOf(Object.class);
		  Iterator<Class<?>> i = classes.iterator();
		  while (i.hasNext()){
			  Class<?> x = i.next();
			  classwork(x);
		  }
	 }
	 
	 public void classwork(Class<?> inClass){
		  Package path = inClass.getClass().getPackage();
		  path.toString();
		  System.out.println(inClass.toString());
		 
	 }

}
```

**Comment by ronmamo** [comment]
fixed
