### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Predicate

### ISSUE THREAD

**Issue by Woolworths** [ronmamo/reflections#72]
Error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Predicate
	at SQLUtils.getDriver(SQLUtils.java:5)
	at Main.main(Main.java:3)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Predicate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Process finished with exit code 1

Code:
https://github.com/Woolworths/reflectionstest

**Comment by Woolworths** [comment]
Windows 7, 64 bit

**Comment by martin-g** [comment]
I'd recommend you to use dependency management tool like Maven or Gradle.
It seems you try to manage the classpath manually by adding jars in IDEA's UI for that.
The exception says that Google Guava library is not in the classpath. 
Better use Maven, define dependency to http://search.maven.org/#artifactdetails%7Corg.reflections%7Creflections%7C0.9.10%7Cjar and everything will come for free.

**Comment by Woolworths** [comment]
I tried using Maven, it did not help. I switched to my Linux and I will use Gradle, hopefully it will work. I never liked Maven anyway.

**Comment by martin-g** [comment]
Update your test app with Maven/Gradle and it will be easier for us to help you.
There is no problem with Reflections so this issue could be closed.

**Comment by Woolworths** [comment]
Now I get this:
bill@bill-H61MA-D3V:~/IdeaProjects/untitled$ java -cp target/untitled-0.9.jar main.java.Main
Exception in thread "main" java.lang.NoClassDefFoundError: org/reflections/Reflections
	at main.java.SQLUtils.getDriver(SQLUtils.java:7)
	at main.java.Main.main(Main.java:5)
Caused by: java.lang.ClassNotFoundException: org.reflections.Reflections
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
bill@bill-H61MA-D3V:~/IdeaProjects/untitled$ ls
out  pom.xml  src  target  untitled.iml

Updated the repo.

**Comment by martin-g** [comment]
It seems your Java is not very strong! ;-)
By using `java -cp target/untitled-0.9.jar main.java.Main` you put only your `untitled-0.9.jar` in the classpath.

With Maven you should use: `mvn8 exec:java -Dexec.mainClass="main.java.Main"`. This way Maven sets up the classpath for you.

mvn dependency:tree shows the list of jars you need in the classpath:
```
:untitled:jar:0.9
[INFO] \- org.reflections:reflections:jar:0.9.10:compile
[INFO]    +- com.google.guava:guava:jar:15.0:compile
[INFO]    +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO]    \- com.google.code.findbugs:annotations:jar:2.0.1:compile
```

**Comment by Woolworths** [comment]
Updated the code, can you check the pom.xml? I ran mvn exec:java -Dexec.mainClass="main.java.Main" and it did NOT work

**Comment by martin-g** [comment]
Hint: the Maven directory structure is: `src/main/java/com/example/Main.java`. Here `com/example` should be the Java package, `main/java` should not be part of the package name.

**Comment by ronmamo** [comment]
@Woolworths - couple of good suggestions, following to @martin-g 's:
1. First of all - Use Intellij by all means. It is your best friend.
2. Start with a working example by cloning from github.
3. Always use a proper build tool - Maven in this case (still, many would argue it is proper/build/tool).
4. Run your code from intellij, forget about the command line.

**Comment by Woolworths** [comment]
@ronmamo yeah cloning would probably be a good idea. Do you know of any simple repo's like mine (https://github.com/Woolworths/reflectionstest) that actually work?

**Comment by Woolworths** [comment]
@ronmamo @martin-g I have fixed the code, it is working as it should. I will keep the code there for fellow programmers. Thank you all for you patience and help!

**Comment by martin-g** [comment]
:+1:
