### ISSUE TITLE
Caused by: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Woolworths** [ronmamo/reflections#75]
Error:
Caused by: java.lang.StackOverflowError
    at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1034)
    at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1013)
    at sun.misc.URLClassPath$JarLoader.findResource(URLClassPath.java:983)
    at sun.misc.URLClassPath$1.next(URLClassPath.java:240)
    at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:250)
    at java.net.URLClassLoader$3$1.run(URLClassLoader.java:601)
    at java.net.URLClassLoader$3$1.run(URLClassLoader.java:599)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader$3.next(URLClassLoader.java:598)
    at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:623)
    at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
    at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
    at org.reflections.util.ClasspathHelper.forResource(ClasspathHelper.java:61)
    at org.reflections.util.ClasspathHelper.forPackage(ClasspathHelper.java:51)
    at com.erby.tab.TabUtils.getTab(TabUtils.java:22)
    at com.erby.tab.tabs.TestTab.<init>(TestTab.java:17)
    at sun.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at com.erby.tab.TabUtils.getTab(TabUtils.java:26)
    at com.erby.tab.tabs.TestTab.<init>(TestTab.java:17)
    at sun.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at com.erby.tab.TabUtils.getTab(TabUtils.java:26)
    at com.erby.tab.tabs.TestTab.<init>(TestTab.java:17)
    at sun.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
    at 

The last few lines repeat a few hundred times. 
Code:
TabUtils.java

```
public class TabUtils {
    public static BaseTab getTab(String prefix) {
        Reflections reflections = new Reflections(ClasspathHelper.forPackage("com.erby.tab.tabs"));

        for(Class<? extends BaseTab> tab : reflections.getSubTypesOf(BaseTab.class)) {
            try {
                BaseTab tmp = (BaseTab) tab.newInstance();

                if(tmp.getPrefix().equalsIgnoreCase(prefix)) {
                    return tmp;
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        return null;
    }
}
```

The behavior the code is experiencing is wildly erratic.
Calling this once works fine:
`TabUtils.getTab("home");`

Assigning it to a variable:
`BaseTab homeTab = TabUtils.getTab("home");`
then calling it does NOT work.

Assigning it and casting it:
`BaseTab homeTab = (BaseTab) TabUtils.getTab("home");`
THEN calling it DOES work.

Background:
TabUtils is in com.erby.tab , the tabs I'm looking for are in com.erby.tab.tabs.
I have also gotten different messages after tinkering with it:
`java.lang.IllegalAccessException: Class com.erby.tab.TabUtils can not access a member of class com.erby.tab.tabs.NewTab with modifiers ""`

**Comment by Woolworths** [comment]
I think it may be due to me using .newInstance() incorrectly. Can anyone give me any pointers?
