### ISSUE TITLE
Method for checking for JAR files fails for certain users

### ISSUE THREAD

**Issue by jrjarrett** [ronmamo/reflections#76]
The way the `Vfs#DefaultUrlTypes` method checks for JAR files fails in certain situations.

Specifically, the one I found is if your username ALSO happens to contain the characters, '.jar'. 

Like me. I'm "jim.jarrett" on my work computer, so plain directories happen to flag as JAR files.

Ex:

    testVfsDir(file:/Users/jim.jarrett/src/reflections/target/test-classes/dir+with%20spaces)
    0 [main] WARN org.reflections.Reflections - could not create Dir using jarFile from url file:/Users/jim.jarrett/src/reflections/target/test-classes/dir+with%20spaces. skipping.
    java.io.FileNotFoundException: /Users/jim.jarrett/src/reflections/target/test-classes/dir+with spaces (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:118)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:212)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.VfsTest.testVfsDir(VfsTest.java:142)
	at org.reflections.VfsTest.dirWithSpaces(VfsTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by jrjarrett** [comment]
I noticed the pull request I submitted to fix this was just closed - could I ask why?
