### ISSUE TITLE
Warning "could not create Vfs.Dir from url" pollutes log, when using ClasspathHelper.forClassLoader()

### ISSUE THREAD

**Issue by ge0ffrey** [ronmamo/reflections#80]
Here's the code I used:
        ConfigurationBuilder builder = new ConfigurationBuilder();
        builder.addUrls(ClasspathHelper.forClassLoader());
        Reflections reflections = new Reflections(builder);

And I get this ugly warning in my log:

11:23:59,868 WARN  [org.reflections.Reflections] (default task-9) could not create Vfs.Dir from url. ignoring the exception and continuing: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) [reflections-0.9.10.jar:]
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) [reflections-0.9.10.jar:]
	at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar:]
	at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar:]
	at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar:]

Workaround:
        ConfigurationBuilder builder = new ConfigurationBuilder();
        builder.addUrls(ClasspathHelper.forPackage(""));
        Reflections reflections = new Reflections(builder);

**Comment by apoorvam** [comment]
Even I'm facing a similar issue. 
Here is my code: 

```
Configuration config = new ConfigurationBuilder()
       .setScanners(new MethodAnnotationsScanner(), new SubTypesScanner())
       .addUrls(ClasspathHelper.forJavaClassPath());
```
And i get this warning in log: 

```
[main] WARN  org.reflections.Reflections  - could not create Dir using directory from url file:/Users/apoorvam/twist/sahi%20project/sahi%20project/libs/com.thoughtworks.twist.driver.sahi_5.0.0.13827-fb7409160b2f96/sahi/docs/sahi_textpad.zip. skipping.
java.lang.RuntimeException: cannot use dir /Users/apoorvam/twist/sahi project/sahi project/libs/com.thoughtworks.twist.driver.sahi_5.0.0.13827-fb7409160b2f96/sahi/docs/sahi_textpad.zip
	at org.reflections.vfs.SystemDir.<init>(SystemDir.java:20)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.createDir(Vfs.java:237)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:231)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
```

Using ClasspathHelper.forPackage() din't help. 
Is there a way to disable this?

**Comment by nonrational** [comment]
After finding this https://issues.apache.org/jira/browse/ISIS-805, I extracted a workaround from [ClassDiscoveryServiceUsingReflections.java](https://git-wip-us.apache.org/repos/asf?p=isis.git;a=blob;f=core/applib/src/main/java/org/apache/isis/applib/services/classdiscovery/ClassDiscoveryServiceUsingReflections.java;h=283f053ddb15bfe32f111d88891602820854415e;hb=283f053ddb15bfe32f111d88891602820854415e). It fixed my problem with `.mar` and `.jnilib` filetypes. 

See `ReflectionsHelper` here: https://gist.github.com/nonrational/287ed109bb0852f982e8

@apoorvam you'll need to add `sahi_textpad.zip` to [line 30](https://gist.github.com/nonrational/287ed109bb0852f982e8#file-reflectionshelper-java-L30).
@ge0ffrey looks like you'll need to add `.so` to [line 30](https://gist.github.com/nonrational/287ed109bb0852f982e8#file-reflectionshelper-java-L30).

**Comment by ge0ffrey** [comment]
It would be nice if the original issue is fixed though, so I can remove the workaround :)

**Comment by bquenin** [comment]
+1

**Comment by hamilton-lima** [comment]
+1

**Comment by hamilton-lima** [comment]
WARNING: could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:231)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at org.reflections.Reflections.<init>(Reflections.java:170)

**Comment by hamilton-lima** [comment]
Based on @karelCemus workaround fixed with this:

```
Reflections reflections = new Reflections(new ConfigurationBuilder().setUrls(ClasspathHelper.forPackage(
				packageName, ClasspathHelper.contextClassLoader(),
				ClasspathHelper.staticClassLoader())) 
);
```

**Comment by sawo** [comment]
+1

**Comment by ptahchiev** [comment]
+1 I think I've got the same. I do the following:
````
final Reflections childReflections = new Reflections(new ConfigurationBuilder().forPackages(packageName).useParallelExecutor());
````

and I get:
````
Caused by: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [war:file:/C:/workspace/nemesis-archetype/target/samplestore.war*/WEB-INF/cl
asses/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialize
d UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections$1.run(Reflections.java:200)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
````

but this exception is seen only on Windows. On Linux it all works fine.

**Comment by kucharzyk** [comment]
I have the same error

```

**Comment by avinashchavanfidel** [comment]
yes , I am checking and trying solutions .Will update you.

**Comment by jctetter** [comment]
I'm getting the same problem. It looks like it has something to do with .useParallelExecutor().  I've used reflections once before with .useParallelExecutor().  Then I tried to use it again later on in my code, also with .useParallelExecutor() then I get the failure. Removing the .useParallelExecutor() fixes the problem.

**Comment by kopax** [comment]
any update on this?

**Comment by stoyle** [comment]
Upgraded to macOS High Sierra, and now my gradle build is starting to show this as well.

This is pretty annoying. Anyways I/we can help out to fix this?

Cheers,
Alf

**Comment by nhoughto** [comment]
I'm getting this all the time when running a gradle build in docker. I presume the docker and overlay filesystem is the difference? Some different file type that isn't supported? 🤷‍♂️

**Comment by tcollinsworth** [comment]
To quiet the logging add the following in src/main/resources/logback.xml

    <logger name="org.reflections.Reflections" level="error"
		additivity="false">
		<appender-ref ref="STDOUT" />
	</logger>

**Comment by DeegC** [comment]
I had this same problem.  What solved my problem was changing my config from using `ClasspathHelper.forClassLoader()` to `ClasspathHelper.forJavaClassPath()`, so:

```
ConfigurationBuilder config = new ConfigurationBuilder()
        .setUrls( ClasspathHelper.forJavaClassPath() )
        .addScanners( TypesAnnotated );
```

**Comment by J4NS-R** [comment]
In my case I got this error because the collection of URLs contained a non-existent directory. Filtering it out solved the problem:

```java
List<URL> urls =
      ClasspathHelper.forJavaClassPath()
            .stream()
            .filter(url -> new File(url.toString()).exists())
            .collect(Collectors.toList());
new Reflections(new ConfigurationBuilder().setUrls(urls));
```

**Comment by philipwhiuk** [comment]
Thanks @J4NS-R that really helped!
